// Generated by CoffeeScript 1.10.0
$(document).ready(function() {
  var initializeSnake, makeGrid, sz;
  $('form#intForm').submit(function() {
    return "elt1 = $('#int1').val()\nalert(elt1)\n\nvalues = [\n	$('#int1').val()\n	$('#int2').val()\n	$('#int3').val()\n]\n\n#alert(values[1])\n\nmaxValue = Math.max values...\n\n#alert(maxValue)\nconsole.log maxValue \n\npercents = [ 100.0* v / maxValue for v in values][0]\nconsole.log percents\nconsole.log percents[0]\n\n#$('#bar1').css(\"background-color\", \"yellow\")\n$('#bar1').css(\"width\", percents[0] + \"%\")\n$('#bar2').css(\"width\", percents[1] + \"%\")\n$('#bar3').css(\"width\", percents[2] + \"%\")\nfalse	";
  });
  sz = 10;
  makeGrid = function() {
    var body, box, col_plus_ind, i, j, k, ref, results, row, row_plus_ind;
    body = $('body');
    results = [];
    for (i = k = 1, ref = sz; 1 <= ref ? k <= ref : k >= ref; i = 1 <= ref ? ++k : --k) {
      row_plus_ind = "row_" + i;
      row = $('<div>');
      row.addClass('row');
      row.addClass(row_plus_ind);
      body.append(row);
      results.push((function() {
        var l, ref1, results1;
        results1 = [];
        for (j = l = 1, ref1 = sz; 1 <= ref1 ? l <= ref1 : l >= ref1; j = 1 <= ref1 ? ++l : --l) {
          col_plus_ind = "col_" + j;
          box = $('<div>');
          box.addClass('box');
          box.addClass(col_plus_ind);
          results1.push(row.append(box));
        }
        return results1;
      })());
    }
    return results;
  };
  initializeSnake = function() {
    var head;
    head = $('.row_10 .col_1');
    head.addClass('selected');
    return $(document).keydown(function(e) {
      switch (e.which) {
        case 37:
          return console.log("YOOOOO");
        case 38:
          break;
        case 39:
          break;
        case 40:
          break;
      }
    });
  };
  makeGrid();
  return initializeSnake();
});
