// Generated by CoffeeScript 1.10.0
$(document).ready(function() {
  var makeGrid, sz;
  $("body").append("<p>Hello world (js)</p>");
  $('form#intForm').submit(function() {
    var elt1, maxValue, percents, v, values;
    elt1 = $('#int1').val();
    alert(elt1);
    values = [$('#int1').val(), $('#int2').val(), $('#int3').val()];
    maxValue = Math.max.apply(Math, values);
    console.log(maxValue);
    percents = [
      (function() {
        var k, len, results;
        results = [];
        for (k = 0, len = values.length; k < len; k++) {
          v = values[k];
          results.push(100.0 * v / maxValue);
        }
        return results;
      })()
    ][0];
    console.log(percents);
    console.log(percents[0]);
    $('#bar1').css("width", percents[0] + "%");
    $('#bar2').css("width", percents[1] + "%");
    $('#bar3').css("width", percents[2] + "%");
    return false;
  });
  sz = 10;
  makeGrid = function() {
    var i, j, k, l, ref, ref1, results;
    results = [];
    for (i = k = 1, ref = sz; 1 <= ref ? k <= ref : k >= ref; i = 1 <= ref ? ++k : --k) {
      $('body').append("<div class='row'>");
      for (j = l = 1, ref1 = sz; 1 <= ref1 ? l <= ref1 : l >= ref1; j = 1 <= ref1 ? ++l : --l) {
        $('body').append("<div class='box'> </div>");
      }
      results.push($('body').append("</div>"));
    }
    return results;
  };
  return makeGrid();
});
